/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: entity.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "entity.pb-c.h"
void   entity_message__init
                     (EntityMessage         *message)
{
  static const EntityMessage init_value = ENTITY_MESSAGE__INIT;
  *message = init_value;
}
size_t entity_message__get_packed_size
                     (const EntityMessage *message)
{
  assert(message->base.descriptor == &entity_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t entity_message__pack
                     (const EntityMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &entity_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t entity_message__pack_to_buffer
                     (const EntityMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &entity_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EntityMessage *
       entity_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EntityMessage *)
     protobuf_c_message_unpack (&entity_message__descriptor,
                                allocator, len, data);
}
void   entity_message__free_unpacked
                     (EntityMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &entity_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor entity_message__field_descriptors[3] =
{
  {
    "type_of_element",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EntityMessage, type_of_element),
    &type_of_element_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EntityMessage, value_type),
    &value_type_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EntityMessage, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned entity_message__field_indices_by_name[] = {
  2,   /* field[2] = name */
  0,   /* field[0] = type_of_element */
  1,   /* field[1] = value_type */
};
static const ProtobufCIntRange entity_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor entity_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EntityMessage",
  "EntityMessage",
  "EntityMessage",
  "",
  sizeof(EntityMessage),
  3,
  entity_message__field_descriptors,
  entity_message__field_indices_by_name,
  1,  entity_message__number_ranges,
  (ProtobufCMessageInit) entity_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
