/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iterator.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "iterator.pb-c.h"
void   iterator_message__init
                     (IteratorMessage         *message)
{
  static const IteratorMessage init_value = ITERATOR_MESSAGE__INIT;
  *message = init_value;
}
size_t iterator_message__get_packed_size
                     (const IteratorMessage *message)
{
  assert(message->base.descriptor == &iterator_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iterator_message__pack
                     (const IteratorMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iterator_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iterator_message__pack_to_buffer
                     (const IteratorMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iterator_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IteratorMessage *
       iterator_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IteratorMessage *)
     protobuf_c_message_unpack (&iterator_message__descriptor,
                                allocator, len, data);
}
void   iterator_message__free_unpacked
                     (IteratorMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iterator_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iterator_message__field_descriptors[2] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IteratorMessage, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_block",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IteratorMessage, read_block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iterator_message__field_indices_by_name[] = {
  0,   /* field[0] = offset */
  1,   /* field[1] = read_block */
};
static const ProtobufCIntRange iterator_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor iterator_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IteratorMessage",
  "IteratorMessage",
  "IteratorMessage",
  "",
  sizeof(IteratorMessage),
  2,
  iterator_message__field_descriptors,
  iterator_message__field_indices_by_name,
  1,  iterator_message__number_ranges,
  (ProtobufCMessageInit) iterator_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
