/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: node.proto */

#ifndef PROTOBUF_C_node_2eproto__INCLUDED
#define PROTOBUF_C_node_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct NodeMessage NodeMessage;


/* --- enums --- */


/* --- messages --- */

struct  NodeMessage
{
  ProtobufCMessage base;
  char *type;
  char *name;
};
#define NODE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&node_message__descriptor) \
    , NULL, NULL }


/* NodeMessage methods */
void   node_message__init
                     (NodeMessage         *message);
size_t node_message__get_packed_size
                     (const NodeMessage   *message);
size_t node_message__pack
                     (const NodeMessage   *message,
                      uint8_t             *out);
size_t node_message__pack_to_buffer
                     (const NodeMessage   *message,
                      ProtobufCBuffer     *buffer);
NodeMessage *
       node_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   node_message__free_unpacked
                     (NodeMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NodeMessage_Closure)
                 (const NodeMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor node_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_node_2eproto__INCLUDED */
