/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: noderesponce.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "noderesponce.pb-c.h"
void   node_responce__init
                     (NodeResponce         *message)
{
  static const NodeResponce init_value = NODE_RESPONCE__INIT;
  *message = init_value;
}
size_t node_responce__get_packed_size
                     (const NodeResponce *message)
{
  assert(message->base.descriptor == &node_responce__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_responce__pack
                     (const NodeResponce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node_responce__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_responce__pack_to_buffer
                     (const NodeResponce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node_responce__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeResponce *
       node_responce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeResponce *)
     protobuf_c_message_unpack (&node_responce__descriptor,
                                allocator, len, data);
}
void   node_responce__free_unpacked
                     (NodeResponce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node_responce__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node_responce__field_descriptors[3] =
{
  {
    "simple_node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NodeResponce, simple_node),
    &simple_node_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationships",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeResponce, n_relationships),
    offsetof(NodeResponce, relationships),
    &relationship_node_responce__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeResponce, n_properties),
    offsetof(NodeResponce, properties),
    &property_responce__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_responce__field_indices_by_name[] = {
  2,   /* field[2] = properties */
  1,   /* field[1] = relationships */
  0,   /* field[0] = simple_node */
};
static const ProtobufCIntRange node_responce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor node_responce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NodeResponce",
  "NodeResponce",
  "NodeResponce",
  "",
  sizeof(NodeResponce),
  3,
  node_responce__field_descriptors,
  node_responce__field_indices_by_name,
  1,  node_responce__number_ranges,
  (ProtobufCMessageInit) node_responce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
