/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: relationship.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "relationship.pb-c.h"
void   relationship_message__init
                     (RelationshipMessage         *message)
{
  static const RelationshipMessage init_value = RELATIONSHIP_MESSAGE__INIT;
  *message = init_value;
}
size_t relationship_message__get_packed_size
                     (const RelationshipMessage *message)
{
  assert(message->base.descriptor == &relationship_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t relationship_message__pack
                     (const RelationshipMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &relationship_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t relationship_message__pack_to_buffer
                     (const RelationshipMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &relationship_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RelationshipMessage *
       relationship_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RelationshipMessage *)
     protobuf_c_message_unpack (&relationship_message__descriptor,
                                allocator, len, data);
}
void   relationship_message__free_unpacked
                     (RelationshipMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &relationship_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor relationship_message__field_descriptors[5] =
{
  {
    "parent_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RelationshipMessage, parent_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "child_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RelationshipMessage, child_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RelationshipMessage, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RelationshipMessage, parent_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "child_type",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RelationshipMessage, child_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned relationship_message__field_indices_by_name[] = {
  1,   /* field[1] = child_id */
  4,   /* field[4] = child_type */
  0,   /* field[0] = parent_id */
  3,   /* field[3] = parent_type */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange relationship_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor relationship_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RelationshipMessage",
  "RelationshipMessage",
  "RelationshipMessage",
  "",
  sizeof(RelationshipMessage),
  5,
  relationship_message__field_descriptors,
  relationship_message__field_indices_by_name,
  1,  relationship_message__number_ranges,
  (ProtobufCMessageInit) relationship_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
