/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: responce.proto */

#ifndef PROTOBUF_C_responce_2eproto__INCLUDED
#define PROTOBUF_C_responce_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "iterator.pb-c.h"
#include "noderesponce.pb-c.h"

typedef struct ResponceMessage ResponceMessage;


/* --- enums --- */


/* --- messages --- */

struct  ResponceMessage
{
  ProtobufCMessage base;
  int32_t status;
  char *message;
  NodeResponce *node;
  IteratorMessage *iterator;
};
#define RESPONCE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&responce_message__descriptor) \
    , 0, NULL, NULL, NULL }


/* ResponceMessage methods */
void   responce_message__init
                     (ResponceMessage         *message);
size_t responce_message__get_packed_size
                     (const ResponceMessage   *message);
size_t responce_message__pack
                     (const ResponceMessage   *message,
                      uint8_t             *out);
size_t responce_message__pack_to_buffer
                     (const ResponceMessage   *message,
                      ProtobufCBuffer     *buffer);
ResponceMessage *
       responce_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   responce_message__free_unpacked
                     (ResponceMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ResponceMessage_Closure)
                 (const ResponceMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor responce_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_responce_2eproto__INCLUDED */
