/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simplenode.proto */

#ifndef PROTOBUF_C_simplenode_2eproto__INCLUDED
#define PROTOBUF_C_simplenode_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SimpleNodeMessage SimpleNodeMessage;


/* --- enums --- */


/* --- messages --- */

struct  SimpleNodeMessage
{
  ProtobufCMessage base;
  char *type;
  int32_t id;
  char *name;
};
#define SIMPLE_NODE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&simple_node_message__descriptor) \
    , NULL, 0, NULL }


/* SimpleNodeMessage methods */
void   simple_node_message__init
                     (SimpleNodeMessage         *message);
size_t simple_node_message__get_packed_size
                     (const SimpleNodeMessage   *message);
size_t simple_node_message__pack
                     (const SimpleNodeMessage   *message,
                      uint8_t             *out);
size_t simple_node_message__pack_to_buffer
                     (const SimpleNodeMessage   *message,
                      ProtobufCBuffer     *buffer);
SimpleNodeMessage *
       simple_node_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   simple_node_message__free_unpacked
                     (SimpleNodeMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SimpleNodeMessage_Closure)
                 (const SimpleNodeMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor simple_node_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_simplenode_2eproto__INCLUDED */
