/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: typeelement.proto */

#ifndef PROTOBUF_C_typeelement_2eproto__INCLUDED
#define PROTOBUF_C_typeelement_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _TypeOfElementProto {
  TYPE_OF_ELEMENT_PROTO__NODE = 0,
  TYPE_OF_ELEMENT_PROTO__RELATIONSHIP = 1,
  TYPE_OF_ELEMENT_PROTO__PROPERTY = 2,
  TYPE_OF_ELEMENT_PROTO__ENTITY = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TYPE_OF_ELEMENT_PROTO)
} TypeOfElementProto;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    type_of_element_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_typeelement_2eproto__INCLUDED */
