/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: typeelement.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "typeelement.pb-c.h"
static const ProtobufCEnumValue type_of_element_proto__enum_values_by_number[4] =
{
  { "NODE", "TYPE_OF_ELEMENT_PROTO__NODE", 0 },
  { "RELATIONSHIP", "TYPE_OF_ELEMENT_PROTO__RELATIONSHIP", 1 },
  { "PROPERTY", "TYPE_OF_ELEMENT_PROTO__PROPERTY", 2 },
  { "ENTITY", "TYPE_OF_ELEMENT_PROTO__ENTITY", 3 },
};
static const ProtobufCIntRange type_of_element_proto__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex type_of_element_proto__enum_values_by_name[4] =
{
  { "ENTITY", 3 },
  { "NODE", 0 },
  { "PROPERTY", 2 },
  { "RELATIONSHIP", 1 },
};
const ProtobufCEnumDescriptor type_of_element_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TypeOfElementProto",
  "TypeOfElementProto",
  "TypeOfElementProto",
  "",
  4,
  type_of_element_proto__enum_values_by_number,
  4,
  type_of_element_proto__enum_values_by_name,
  1,
  type_of_element_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
