/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: valuetype.proto */

#ifndef PROTOBUF_C_valuetype_2eproto__INCLUDED
#define PROTOBUF_C_valuetype_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _ValueTypeProto {
  VALUE_TYPE_PROTO__INT = 0,
  VALUE_TYPE_PROTO__FLOAT = 1,
  VALUE_TYPE_PROTO__STRING = 2,
  VALUE_TYPE_PROTO__BOOL = 3,
  VALUE_TYPE_PROTO__VOID = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(VALUE_TYPE_PROTO)
} ValueTypeProto;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    value_type_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_valuetype_2eproto__INCLUDED */
