/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: valuetype.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "valuetype.pb-c.h"
static const ProtobufCEnumValue value_type_proto__enum_values_by_number[5] =
{
  { "INT", "VALUE_TYPE_PROTO__INT", 0 },
  { "FLOAT", "VALUE_TYPE_PROTO__FLOAT", 1 },
  { "STRING", "VALUE_TYPE_PROTO__STRING", 2 },
  { "BOOL", "VALUE_TYPE_PROTO__BOOL", 3 },
  { "VOID", "VALUE_TYPE_PROTO__VOID", 4 },
};
static const ProtobufCIntRange value_type_proto__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex value_type_proto__enum_values_by_name[5] =
{
  { "BOOL", 3 },
  { "FLOAT", 1 },
  { "INT", 0 },
  { "STRING", 2 },
  { "VOID", 4 },
};
const ProtobufCEnumDescriptor value_type_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ValueTypeProto",
  "ValueTypeProto",
  "ValueTypeProto",
  "",
  5,
  value_type_proto__enum_values_by_number,
  5,
  value_type_proto__enum_values_by_name,
  1,
  value_type_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
