/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: entity.proto */

#ifndef PROTOBUF_C_entity_2eproto__INCLUDED
#define PROTOBUF_C_entity_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "typeelement.pb-c.h"
#include "valuetype.pb-c.h"

typedef struct EntityMessage EntityMessage;


/* --- enums --- */


/* --- messages --- */

struct  EntityMessage
{
  ProtobufCMessage base;
  TypeOfElementProto type_of_element;
  ValueTypeProto value_type;
  char *name;
};
#define ENTITY_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&entity_message__descriptor) \
    , TYPE_OF_ELEMENT_PROTO__NODE, VALUE_TYPE_PROTO__INT, NULL }


/* EntityMessage methods */
void   entity_message__init
                     (EntityMessage         *message);
size_t entity_message__get_packed_size
                     (const EntityMessage   *message);
size_t entity_message__pack
                     (const EntityMessage   *message,
                      uint8_t             *out);
size_t entity_message__pack_to_buffer
                     (const EntityMessage   *message,
                      ProtobufCBuffer     *buffer);
EntityMessage *
       entity_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   entity_message__free_unpacked
                     (EntityMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*EntityMessage_Closure)
                 (const EntityMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor entity_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_entity_2eproto__INCLUDED */
