/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: filter.proto */

#ifndef PROTOBUF_C_filter_2eproto__INCLUDED
#define PROTOBUF_C_filter_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct FilterMessage FilterMessage;


/* --- enums --- */

typedef enum _FieldProto {
  FIELD_PROTO__ID = 0,
  FIELD_PROTO__NAME = 1,
  FIELD_PROTO__VALUE = 2,
  FIELD_PROTO__TYPE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FIELD_PROTO)
} FieldProto;
typedef enum _CompareTypeProto {
  COMPARE_TYPE_PROTO__GREATER = 0,
  COMPARE_TYPE_PROTO__LOWER = 1,
  COMPARE_TYPE_PROTO__EQUAL = 2,
  COMPARE_TYPE_PROTO__NOT_EQUAL = 3,
  COMPARE_TYPE_PROTO__ALL = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMPARE_TYPE_PROTO)
} CompareTypeProto;

/* --- messages --- */

struct  FilterMessage
{
  ProtobufCMessage base;
  FieldProto field;
  char *value;
  CompareTypeProto type;
  char *type_element;
};
#define FILTER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&filter_message__descriptor) \
    , FIELD_PROTO__ID, NULL, COMPARE_TYPE_PROTO__GREATER, NULL }


/* FilterMessage methods */
void   filter_message__init
                     (FilterMessage         *message);
size_t filter_message__get_packed_size
                     (const FilterMessage   *message);
size_t filter_message__pack
                     (const FilterMessage   *message,
                      uint8_t             *out);
size_t filter_message__pack_to_buffer
                     (const FilterMessage   *message,
                      ProtobufCBuffer     *buffer);
FilterMessage *
       filter_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   filter_message__free_unpacked
                     (FilterMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FilterMessage_Closure)
                 (const FilterMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    field_proto__descriptor;
extern const ProtobufCEnumDescriptor    compare_type_proto__descriptor;
extern const ProtobufCMessageDescriptor filter_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_filter_2eproto__INCLUDED */
