/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iterator.proto */

#ifndef PROTOBUF_C_iterator_2eproto__INCLUDED
#define PROTOBUF_C_iterator_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct IteratorMessage IteratorMessage;


/* --- enums --- */


/* --- messages --- */

struct  IteratorMessage
{
  ProtobufCMessage base;
  uint32_t offset;
  uint32_t read_block;
};
#define ITERATOR_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iterator_message__descriptor) \
    , 0, 0 }


/* IteratorMessage methods */
void   iterator_message__init
                     (IteratorMessage         *message);
size_t iterator_message__get_packed_size
                     (const IteratorMessage   *message);
size_t iterator_message__pack
                     (const IteratorMessage   *message,
                      uint8_t             *out);
size_t iterator_message__pack_to_buffer
                     (const IteratorMessage   *message,
                      ProtobufCBuffer     *buffer);
IteratorMessage *
       iterator_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iterator_message__free_unpacked
                     (IteratorMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IteratorMessage_Closure)
                 (const IteratorMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor iterator_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_iterator_2eproto__INCLUDED */
