/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: operation.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "operation.pb-c.h"
static const ProtobufCEnumValue operation_proto__enum_values_by_number[7] =
{
  { "CREATE_NODE", "OPERATION_PROTO__CREATE_NODE", 0 },
  { "INSERT_NODE", "OPERATION_PROTO__INSERT_NODE", 1 },
  { "UPDATE_NODE", "OPERATION_PROTO__UPDATE_NODE", 2 },
  { "SELECT_NODE", "OPERATION_PROTO__SELECT_NODE", 3 },
  { "DELETE_NODE", "OPERATION_PROTO__DELETE_NODE", 4 },
  { "CREATE_ENTITY", "OPERATION_PROTO__CREATE_ENTITY", 5 },
  { "DELETE_ENTITY", "OPERATION_PROTO__DELETE_ENTITY", 6 },
};
static const ProtobufCIntRange operation_proto__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex operation_proto__enum_values_by_name[7] =
{
  { "CREATE_ENTITY", 5 },
  { "CREATE_NODE", 0 },
  { "DELETE_ENTITY", 6 },
  { "DELETE_NODE", 4 },
  { "INSERT_NODE", 1 },
  { "SELECT_NODE", 3 },
  { "UPDATE_NODE", 2 },
};
const ProtobufCEnumDescriptor operation_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OperationProto",
  "OperationProto",
  "OperationProto",
  "",
  7,
  operation_proto__enum_values_by_number,
  7,
  operation_proto__enum_values_by_name,
  1,
  operation_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
