/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: property.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "property.pb-c.h"
void   property_message__init
                     (PropertyMessage         *message)
{
  static const PropertyMessage init_value = PROPERTY_MESSAGE__INIT;
  *message = init_value;
}
size_t property_message__get_packed_size
                     (const PropertyMessage *message)
{
  assert(message->base.descriptor == &property_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t property_message__pack
                     (const PropertyMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &property_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t property_message__pack_to_buffer
                     (const PropertyMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &property_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PropertyMessage *
       property_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PropertyMessage *)
     protobuf_c_message_unpack (&property_message__descriptor,
                                allocator, len, data);
}
void   property_message__free_unpacked
                     (PropertyMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &property_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor property_message__field_descriptors[5] =
{
  {
    "value_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PropertyMessage, value_type),
    &value_type_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PropertyMessage, subject_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PropertyMessage, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PropertyMessage, subject_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PropertyMessage, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned property_message__field_indices_by_name[] = {
  1,   /* field[1] = subject_id */
  3,   /* field[3] = subject_type */
  2,   /* field[2] = type */
  4,   /* field[4] = value */
  0,   /* field[0] = value_type */
};
static const ProtobufCIntRange property_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor property_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PropertyMessage",
  "PropertyMessage",
  "PropertyMessage",
  "",
  sizeof(PropertyMessage),
  5,
  property_message__field_descriptors,
  property_message__field_indices_by_name,
  1,  property_message__number_ranges,
  (ProtobufCMessageInit) property_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
