/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: propertyresponce.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "propertyresponce.pb-c.h"
void   property_responce__init
                     (PropertyResponce         *message)
{
  static const PropertyResponce init_value = PROPERTY_RESPONCE__INIT;
  *message = init_value;
}
size_t property_responce__get_packed_size
                     (const PropertyResponce *message)
{
  assert(message->base.descriptor == &property_responce__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t property_responce__pack
                     (const PropertyResponce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &property_responce__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t property_responce__pack_to_buffer
                     (const PropertyResponce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &property_responce__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PropertyResponce *
       property_responce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PropertyResponce *)
     protobuf_c_message_unpack (&property_responce__descriptor,
                                allocator, len, data);
}
void   property_responce__free_unpacked
                     (PropertyResponce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &property_responce__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor property_responce__field_descriptors[3] =
{
  {
    "value_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PropertyResponce, value_type),
    &value_type_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PropertyResponce, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PropertyResponce, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned property_responce__field_indices_by_name[] = {
  1,   /* field[1] = type */
  2,   /* field[2] = value */
  0,   /* field[0] = value_type */
};
static const ProtobufCIntRange property_responce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor property_responce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PropertyResponce",
  "PropertyResponce",
  "PropertyResponce",
  "",
  sizeof(PropertyResponce),
  3,
  property_responce__field_descriptors,
  property_responce__field_indices_by_name,
  1,  property_responce__number_ranges,
  (ProtobufCMessageInit) property_responce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
