/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: relationship.proto */

#ifndef PROTOBUF_C_relationship_2eproto__INCLUDED
#define PROTOBUF_C_relationship_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RelationshipMessage RelationshipMessage;


/* --- enums --- */


/* --- messages --- */

struct  RelationshipMessage
{
  ProtobufCMessage base;
  int32_t parent_id;
  int32_t child_id;
  char *type;
  char *parent_type;
  char *child_type;
};
#define RELATIONSHIP_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&relationship_message__descriptor) \
    , 0, 0, NULL, NULL, NULL }


/* RelationshipMessage methods */
void   relationship_message__init
                     (RelationshipMessage         *message);
size_t relationship_message__get_packed_size
                     (const RelationshipMessage   *message);
size_t relationship_message__pack
                     (const RelationshipMessage   *message,
                      uint8_t             *out);
size_t relationship_message__pack_to_buffer
                     (const RelationshipMessage   *message,
                      ProtobufCBuffer     *buffer);
RelationshipMessage *
       relationship_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   relationship_message__free_unpacked
                     (RelationshipMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RelationshipMessage_Closure)
                 (const RelationshipMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor relationship_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_relationship_2eproto__INCLUDED */
