/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: relationshipnoderesponce.proto */

#ifndef PROTOBUF_C_relationshipnoderesponce_2eproto__INCLUDED
#define PROTOBUF_C_relationshipnoderesponce_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "simplenode.pb-c.h"

typedef struct RelationshipNodeResponce RelationshipNodeResponce;


/* --- enums --- */


/* --- messages --- */

struct  RelationshipNodeResponce
{
  ProtobufCMessage base;
  char *relation_type;
  SimpleNodeMessage *node;
};
#define RELATIONSHIP_NODE_RESPONCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&relationship_node_responce__descriptor) \
    , NULL, NULL }


/* RelationshipNodeResponce methods */
void   relationship_node_responce__init
                     (RelationshipNodeResponce         *message);
size_t relationship_node_responce__get_packed_size
                     (const RelationshipNodeResponce   *message);
size_t relationship_node_responce__pack
                     (const RelationshipNodeResponce   *message,
                      uint8_t             *out);
size_t relationship_node_responce__pack_to_buffer
                     (const RelationshipNodeResponce   *message,
                      ProtobufCBuffer     *buffer);
RelationshipNodeResponce *
       relationship_node_responce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   relationship_node_responce__free_unpacked
                     (RelationshipNodeResponce *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RelationshipNodeResponce_Closure)
                 (const RelationshipNodeResponce *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor relationship_node_responce__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_relationshipnoderesponce_2eproto__INCLUDED */
