/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: relationshipnoderesponce.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "relationshipnoderesponce.pb-c.h"
void   relationship_node_responce__init
                     (RelationshipNodeResponce         *message)
{
  static const RelationshipNodeResponce init_value = RELATIONSHIP_NODE_RESPONCE__INIT;
  *message = init_value;
}
size_t relationship_node_responce__get_packed_size
                     (const RelationshipNodeResponce *message)
{
  assert(message->base.descriptor == &relationship_node_responce__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t relationship_node_responce__pack
                     (const RelationshipNodeResponce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &relationship_node_responce__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t relationship_node_responce__pack_to_buffer
                     (const RelationshipNodeResponce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &relationship_node_responce__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RelationshipNodeResponce *
       relationship_node_responce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RelationshipNodeResponce *)
     protobuf_c_message_unpack (&relationship_node_responce__descriptor,
                                allocator, len, data);
}
void   relationship_node_responce__free_unpacked
                     (RelationshipNodeResponce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &relationship_node_responce__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor relationship_node_responce__field_descriptors[2] =
{
  {
    "relation_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RelationshipNodeResponce, relation_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RelationshipNodeResponce, node),
    &simple_node_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned relationship_node_responce__field_indices_by_name[] = {
  1,   /* field[1] = node */
  0,   /* field[0] = relation_type */
};
static const ProtobufCIntRange relationship_node_responce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor relationship_node_responce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RelationshipNodeResponce",
  "RelationshipNodeResponce",
  "RelationshipNodeResponce",
  "",
  sizeof(RelationshipNodeResponce),
  2,
  relationship_node_responce__field_descriptors,
  relationship_node_responce__field_indices_by_name,
  1,  relationship_node_responce__number_ranges,
  (ProtobufCMessageInit) relationship_node_responce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
