/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   request_message__init
                     (RequestMessage         *message)
{
  static const RequestMessage init_value = REQUEST_MESSAGE__INIT;
  *message = init_value;
}
size_t request_message__get_packed_size
                     (const RequestMessage *message)
{
  assert(message->base.descriptor == &request_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_message__pack
                     (const RequestMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_message__pack_to_buffer
                     (const RequestMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestMessage *
       request_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestMessage *)
     protobuf_c_message_unpack (&request_message__descriptor,
                                allocator, len, data);
}
void   request_message__free_unpacked
                     (RequestMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request_message__field_descriptors[10] =
{
  {
    "operation",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, operation),
    &operation_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, type),
    &type_of_element_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, filter),
    &filter_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, entity),
    &entity_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, node),
    &node_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationship",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, relationship),
    &relationship_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, property),
    &property_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationships",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RequestMessage, n_relationships),
    offsetof(RequestMessage, relationships),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RequestMessage, n_properties),
    offsetof(RequestMessage, properties),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iterator",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RequestMessage, iterator),
    &iterator_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_message__field_indices_by_name[] = {
  3,   /* field[3] = entity */
  2,   /* field[2] = filter */
  9,   /* field[9] = iterator */
  4,   /* field[4] = node */
  0,   /* field[0] = operation */
  8,   /* field[8] = properties */
  6,   /* field[6] = property */
  5,   /* field[5] = relationship */
  7,   /* field[7] = relationships */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange request_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor request_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestMessage",
  "RequestMessage",
  "RequestMessage",
  "",
  sizeof(RequestMessage),
  10,
  request_message__field_descriptors,
  request_message__field_indices_by_name,
  1,  request_message__number_ranges,
  (ProtobufCMessageInit) request_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
