/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simplenode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "simplenode.pb-c.h"
void   simple_node_message__init
                     (SimpleNodeMessage         *message)
{
  static const SimpleNodeMessage init_value = SIMPLE_NODE_MESSAGE__INIT;
  *message = init_value;
}
size_t simple_node_message__get_packed_size
                     (const SimpleNodeMessage *message)
{
  assert(message->base.descriptor == &simple_node_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simple_node_message__pack
                     (const SimpleNodeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simple_node_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simple_node_message__pack_to_buffer
                     (const SimpleNodeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simple_node_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimpleNodeMessage *
       simple_node_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimpleNodeMessage *)
     protobuf_c_message_unpack (&simple_node_message__descriptor,
                                allocator, len, data);
}
void   simple_node_message__free_unpacked
                     (SimpleNodeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simple_node_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor simple_node_message__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SimpleNodeMessage, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SimpleNodeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SimpleNodeMessage, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simple_node_message__field_indices_by_name[] = {
  1,   /* field[1] = id */
  2,   /* field[2] = name */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange simple_node_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor simple_node_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SimpleNodeMessage",
  "SimpleNodeMessage",
  "SimpleNodeMessage",
  "",
  sizeof(SimpleNodeMessage),
  3,
  simple_node_message__field_descriptors,
  simple_node_message__field_indices_by_name,
  1,  simple_node_message__number_ranges,
  (ProtobufCMessageInit) simple_node_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
